# Generated by Django 4.2.5 on 2024-03-01 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Investment', models.CharField(max_length=100)),
                ('Created_At', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
